import 'package:flutter/material.dart';

List<String> distritos = [
  "Alto Selva Alegre",
  "Arequipa",
  "Cayma",
  "Cerro Colorado",
  "Characato",
  "Chiguata",
  "Jacobo Hunter",
  "José Luis Bustamante y Rivero",
  "La Joya",
  "Mariano Melgar",
  "Miraflores",
  "Mollebaya",
  "Paucarpata",
  "Pocsi",
  "Polobaya",
  "Quequeña",
  "Sabandía",
  "Sachaca",
  "San Juan de Siguas",
  "San Juan de Tarucani",
  "Santa Isabel de Siguas",
  "Santa Rita de Siguas",
  "Socabaya",
  "Tiabaya",
  "Uchumayo",
  "Vítor",
  "Yanahuara",
  "Yarabamba",
  "Yura"
];
